version: "3.8"

networks:
  widget_demo_network:
    driver: bridge
    name: widget_demo_network
    ipam:
      config:
        - subnet: ${WIDGET_SUBNET}
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: web_demo_widget
    volumes:
      - ./app:/app
      - /app/node_modules
    env_file:
      - .env
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    networks:
      widget_demo_network:
        ipv4_address: ${WEB_IP}

  nginx:
    build:
      context: ./nginx
    container_name: nextjs_nginx
    ports:
      - "${NGINX_PORT}:443"
    depends_on:
      - web
    networks:
      widget_demo_network:
        ipv4_address: ${NGINX_IP}
