FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/default.conf
COPY certs/demo.widget.api.crt /etc/ssl/certs/demo.widget.api.crt
COPY certs/demo.widget.api.key /etc/ssl/private/demo.widget.api.key

